# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 106dcfc4d9c3499d05487cba0486633239945fb99625d4b658c5131fe574b97b84e4413fef796e59687ead122c5d7afec6ed1f37c8437f1d9148c57a239ce603

test:
  secret_key_base: 5a2cd37521b4c580cf6f3a7036818787d64bebd27448303be03e7f7b3d383b0c44aaf5760880b5c098f4d8a1b6fdc78eda999378a22233cc698e1fbcce5b9ba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
